### PR TITLE
Update Proton-GE to 7-27

### PR DESCRIPTION
**Pull request by NikitaPuzyryov**

### CODE REVIEW

**Comment by NikitaPuzyryov** [comment]
Hmm. Apex Legends stopped working on this version — crash at launch. Any hints where this should be reported to?

**Comment by PedroHLC** [comment]
@NikitaPuzyryov GE's Discord server: https://discord.gg/6y3BdzC

**Comment by NikitaPuzyryov** [comment]
Talking with GE devs revealed that there might be an issue with FSR. I'd suggest skipping this version.

**Comment by PedroHLC** [comment]
Please comment about this on [the AUR page](https://aur.archlinux.org/packages/proton-ge-custom-bin/) so more people knows.

**Comment by NikitaPuzyryov** [comment]
@PedroHLC done!

Linking some context in Discord:
> ok so both of you are failing at 720p

> might actually be FSR, the game has issues with 1080p but only when FSR is disabled, and I know FFXIV has a problem with 720p

https://discord.com/channels/110175050006577152/522638111042437132/1001533844920488018

**Pull request closed without merging**
