### PR TITLE
Upgrade ge-proton to version 7_49

### PR DESCRIPTION
**Pull request by sigboe**

### CODE REVIEW

**Comment by dr460nf1r3** [comment]
.SRCINFO shall be updated as well :)

**Comment by sigboe** [comment]
There we go thanks @dr460nf1r3

**Comment by dr460nf1r3** [comment]
Did you do it manually? I don't see the checksums being updated 👀

**Comment by Jaja83** [comment]
Sorry, I already updated the aur to 7-49 - I did not see your MR. Please do not merge.

**Comment by dr460nf1r3** [comment]
Ah that's even better, thank you to both of you guys :)

**Comment by sigboe** [comment]
Sorry for not knowing what to update, next time I see an opening I'll try to do it properly.

**Comment by dr460nf1r3** [comment]
Hey, thanks for contributing! :) 
As a general tip, when updating PKGBUILDs on AUR always run `makepkg --printsrcinfo` > .SRCINFO` in the current folder to automatically update the .SRCINFO from the PKGBUILD 😊

**Comment by PedroHLC** [comment]
I've tried to add @Jaja83 as a maintainer, in hope this will not happen again. But @dr460nf1r3 we should fix the bot...

**Comment by sigboe** [comment]
@dr460nf1r3 Thank you! so the steps are (in case more eager people are reading)
```bash
vim PKGBUILD #update the release version in PKGBUILD
updpkgsums #to update the checksum in the PKGBUILD
makepkg --printsrcinfo > .SRCINFO #to update the .SRCINFO
```
thanks!

**Comment by dr460nf1r3** [comment]
> But @dr460nf1r3 we should fix the bot...

Yes, absolutely! Gotta annoy @Edu4rdSHL :yum: 



> Thank you! so the steps are (in case more eager people are reading)

That's correct! Glad I could be of assistance :)

**Comment by Jaja83** [comment]
@sigboe nice list, but you also may update the changelog. some tools (even pacman) can display it so we keep it up-to-date, too.

@dr460nf1r3 I do not know what you refer to when blameing the bot, but sigboe did actually place the MR even before I pushed my commit to aur. This is because the MR was not there in the first place when I started and quite some time is needed to the test the pkgbuild, dependency analysis (that used to change regularly) and the actual build to work properly with some games I have. Afterwards, I pushed it without a further look here. So it was my fault.

**Comment by dr460nf1r3** [comment]
@Jaja83 don't worry about it, we were referring to the GitHub action that was supposed to automatically push to AUR when merging a PR. Everything is fine! 😊

**Comment by sigboe** [comment]
@Jaja83 thanks, edited my comment if I use it to remember in the future

**Pull request closed without merging**
