### PR TITLE
Add .gitignore and bump revision

### PR DESCRIPTION
**Pull request by tjhexf**
Added a .gitignore per #26 (thanks quin47) and bumped the revision to reflect the changes in the package.

### CODE REVIEW

**Comment by PedroHLC** [comment]
Closed with 2ceb5e7b697bf325728e1d5e814c3e28d37f43fb

**Comment by Jaja83** [comment]
I am not too happy with the .gitignore being checked-in:
 
You may not know what files someone keeps in the build dir. I have had to move some small scripts out if it just because of this PR. It would not have made sense to add them in the gitignore for everyone, so this is more of a custom setting.
Some environments like .vscode also add some additional files... 

Anyway, I did not revert this change. 
Since the AUR is a community project, I surely respect your work and I am happy that chaotic-aur (and all the people) are helping to keep up with the frequent upstream updates.
Just wanted you to know. 

FYI @quin47, @PedroHLC

**Comment by tjhexf** [comment]
Sorry, i had no ill intent with this one. Do you think it would be better to individually add the default generated build artifacts in the build folder, instead of adding the build folder itself to the .gitignore?
@Jaja83

**Comment by PedroHLC** [comment]
Sorry, @Jaja83 I didn't think someone could be using this as a developer.

**Comment by Jaja83** [comment]
No need to worry, no big deal :)
@tjhexf no, it's fine like you did it.

**Comment by gyscos** [comment]
Note that `.gitignore` are _meant_ to be checked in. If you want local rules instead, use `.git/info/exclude`.

**Pull request closed without merging**
